services:
  qwen:
    image: ollama/ollama:latest
    container_name: qwen
    volumes:
      - ./ollama:/root/.ollama
    ports:
      - "11434:11434"
    environment:
      OLLAMA_MODELS: "qwen2.5-coder:7b-instruct-q4_0"
      OLLAMA_MAX_CONTEXT: "32768"
      CUDA_VISIBLE_DEVICES: ""           # силами строкової змінної вимикаємо GPU
    # ● не використовує GPU (видалено “deploy.resources.reservations.devices”) ▶️
 
  appium:
    build: ./agent/appium               # власний Dockerfile із встановленим плагіном
    container_name: appium
    ports:
      - "4723:4723"

  agent:
    build: ./agent
    container_name: automation-agent
    depends_on:
      - qwen
      - appium
    environment:
      OLLAMA_BASE: http://qwen:11434
      APPIUM_SERVER: http://appium:4723/wd/hub
      ADB_HOST: blissvm       # з’єднання до BlissOS по ADB/TCP
      ADB_PORT: "5555"
      LANGCHAIN_AGENT_TOOLS: "appium,adb_shell"
    volumes:
      - ./agent/logs:/_logs
    ports:
      - "8000:8000"           # якщо FastAPI — на порту 8000

networks:
  default:
    name: automation-net
